# Generated by Django 4.1.1 on 2022-10-06 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_characteristictype_parentcharacteristictype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parentcharacteristictype',
            old_name='title',
            new_name='name',
        ),
    ]
