# Generated by Django 4.1.1 on 2022-10-06 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_characteristictype_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parentcharacteristic',
            old_name='title',
            new_name='name',
        ),
    ]
