# Generated by Django 4.1.1 on 2022-10-18 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_category_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryPlaceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('childId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childId', to='store.categorytable')),
                ('parentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parentId', to='store.categorytable')),
            ],
        ),
    ]
