# Generated by Django 4.1.1 on 2022-10-19 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_categorytable_categoryplacetable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryplacetable',
            options={'ordering': ('level',)},
        ),
        migrations.AddField(
            model_name='categoryplacetable',
            name='categoryId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='store.categorytable'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoryplacetable',
            name='childId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='store.categorytable'),
        ),
        migrations.AlterField(
            model_name='categoryplacetable',
            name='parentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='store.categorytable'),
        ),
    ]
