# Generated by Django 4.1.1 on 2022-10-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_categorytable_name_alter_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytable',
            name='final_level',
            field=models.BooleanField(default=False),
        ),
    ]
