# Generated by Django 4.1.1 on 2022-10-23 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_categorytable_final_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog_1',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.DeleteModel(
            name='Catalog_0',
        ),
        migrations.DeleteModel(
            name='Catalog_1',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
