# Generated by Django 4.1.1 on 2022-10-23 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0014_remove_catalog_1_parent_remove_category_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now=True)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField(null=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='admin_create', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='store.product')),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='admin_update', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
