# Generated by Django 4.1.1 on 2022-10-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_priceproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceproduct',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='priceproduct',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
