# Generated by Django 4.1.1 on 2022-10-24 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0017_product_create_by_alter_product_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='create_by',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='product',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='updated_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
