# Generated by Django 4.1.1 on 2022-10-24 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_remove_priceproduct_product_alter_brand_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceProductRepresent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='store.priceproduct')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='store.product')),
            ],
        ),
    ]
