# Generated by Django 4.1.1 on 2022-10-27 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0020_priceproductrepresent'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('term_of_use', models.CharField(max_length=255)),
                ('advantages', models.TextField()),
                ('limitations', models.TextField()),
                ('comments', models.TextField()),
                ('additionals', models.TextField()),
                ('photos', models.TextField()),
                ('positive_likes', models.IntegerField()),
                ('negative_likes', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='feedback_product', to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeedBackOpinionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FeedBackVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive_vote', models.IntegerField(blank=True, null=True)),
                ('negative_vote', models.IntegerField(blank=True, null=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='feedback_voted', to='store.feedback')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBackOpinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion', models.IntegerField()),
                ('appearance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_opinion', to='store.feedbackopiniontype')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='feedbacks_opinion', to='store.feedback')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBackCascade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_feedback', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='feedback_child', to='store.feedback')),
                ('current_feedback', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='feedback_current', to='store.feedback')),
                ('parent_feedback', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='feedback_parent', to='store.feedback')),
            ],
        ),
    ]
