# Generated by Django 4.1.1 on 2022-10-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_feedback_feedbackopiniontype_brand_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='negative_likes',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='positive_likes',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='additionals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='advantages',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='limitations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='photos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
